### ISSUE TITLE
NAMD Output is not matching with the output files.

### ISSUE THREAD

**Issue by MrigankaParasar** [AkimovLab/Project_NBRA-BL-NA-MD_SiNCs#1]
0p8nm_H1_step2 was uncompressed and the path of the hvib files was specified in NAMD/08nm/H1/1eV/run_step4.py

Original output file :
[_out_Markov_.txt](https://github.com/AkimovLab/Project_NBRA-BL-NA-MD_SiNCs/files/6834288/_out_Markov_.txt)

Output file after running run_step4.py on my system (No population and energy changes) :
[_out_Markov_new.txt](https://github.com/AkimovLab/Project_NBRA-BL-NA-MD_SiNCs/files/6834290/_out_Markov_new.txt)

**Comment by alexvakimov** [comment]
Hi @MrigankaParasar , could you please provide more details on what you are trying to do and what files and code version you are using. Potentially, we could discuss this more on Slack (Quantum Dynamics Hub).

**Comment by MrigankaParasar** [comment]
I am using this project as a guide for simulating photo induced charge transfer using NBRA FSSH in Libra. The electronic structure calculations are being done using dftb+. 

I wrote the driver code for my project and ran the FSSH calculations. The output didn't indicate any population change as I got a column of 1.00000 in the P_SH column for the initial state. 

Surprisingly, running the driver code in this repo (not written by me), also gives me the same column of 1s, indicating no population change. In this case, all the files were provided in this repo itself. 

I am using the latest release of Libra.

Please let me know the Slack channel in which we can discuss such issues. Thank you.

**Comment by alexvakimov** [comment]
I PM-ed you on the Quantum-Dynamics-Hub Slack workspace. Please make sure your notifications aren't turned off.
